### ISSUE TITLE
Will this work to backup remote mysql servers?

### ISSUE THREAD

**Issue by mrcarl79** [cbaerike/MySQL-Backup-Manager#11]
I wanted to install it on windows but to backup a remote mysql server, is this possible? I get an error when I try to install and assume this is why because there is no mysql installed locally. Thanks, C

**Comment by cbaerike** [comment]
Hi,

You'll need a local install of the MySQL or MariaDB binaries. MySQL Backup Manager requires the mysqldmp.exe file to take backups.

Your actual database can be on any server, as long as the backup server has access to it. Remote servers are not an issue.
