### ISSUE TITLE
Installation Error with installer v1.4.1

### ISSUE THREAD

**Issue by crackalak** [cbaerike/MySQL-Backup-Manager#5]
Installing on Windows 7 32Bit and getting the following error:

Error 1001. An exception occurred in the OnAfterInstall event handler of MySQLBackupService.ProjectInstaller. --> Object reference not set to an instance of an object.

The MySQL Backup Service was installed but the installer didn't start it. I can manually start the service without errors while the installer error message is still showing.
The bin path was not added to the PATH envrionment variable.

**Comment by sholyoaked** [comment]
I can help on this one - it is an issue where the program cannot find the mysql dump utility for creating the backup.

Here is where you go – First right click ‘Computer’ on the start menu and hit properties, then click advanced system properties on the left. (This may be different in server 2012 and Windows 8-8.1)

Then click the environment variables button at the bottom.

After this, scroll down in the second half of the window until you see 'Path' and then double-click on it.

Add this to the end (changing to your MySQL Directory where below 5.1 is the example):

;C:\Program Files\MySQL\MySQL Server 5.1\bin
(with the semi-colon at the beginning to separate it from the previous command)

For more information see below:

http://dev.mysql.com/doc/mysql-windows-excerpt/5.1/en/mysql-installation-windows-path.html

**Comment by crackalak** [comment]
Ah my fault then, tried installing it on a computer that didn't have MySQL server installed! Thanks

**Comment by sholyoaked** [comment]
That is ok :)
