### ISSUE TITLE
Modified DB, Removed, Re-added now host seems to be ignored?

### ISSUE THREAD

**Issue by 89gsc** [cbaerike/MySQL-Backup-Manager#8]
I installed this software to backup around 40 databases and its great so far! I have noticed a few visual issues which I will add at the end of this post but the main issue I am having now:
- ERROR - Got error: 2049: Connection using old (pre-4.1.1) authentication protocol refused (client option 'secure_auth' enabled) when trying to connect

I get this error with many of my older databases, to resolve it I need to remake the user account I setup this seems to remake the user without pre-4.1.1 auth, this isn't a major issue I just wanted to note it in case others are having that problem. 
- ERROR - Got error: 1044: Access denied for user 'doricfest'@'%' to database 'doric' when selecting the database

With the above error I got this after I added a database with the wrong host name, I tried to modify it which didn't save the modified details at all, so after the modified attempt didn't work I removed the database and re-added it, by the looks of it, it is under the correct host section but the error @% would suggest its ignoring the host? I couldn't find where the database settings are kept to see if it was something I could double check so I am not sure whats happening.   

I had 2 small visual issues I thought may be worth mentioning, Modifying a database, should this not display the modify fields filled in and not blank?

The database page which shows databases is not scroll-able so you need to minimize hosts to see lower ones, I don't know if it becomes scroll able when you have enough different hosts to fill this space as I am 1 host away from this being a problem so can't tell yet. 

If you need me to test anything please let me know, and thanks for forking this great software I had far too many issues with the Master branch so I appreciate all the time you have put in to keep this up to date.

**Comment by 89gsc** [comment]
Just noticed modifying doesn't seem to work at all tried changing 2 databases and retesting them and they are using the usernames they were first setup with but were just modified.

**Comment by 89gsc** [comment]
Ok more to my first post, I had to remove / re-add another DB.

Log shows: 

2015-06-08 11:21 - INFO - Backup job scheduled for database: wavesfm @ 213.***.200.76

Then testing:

2015-06-08 11:21 - ERROR - Got error: 1045: Access denied for user 'wavesfm'@'92.***.80.102' (using password: YES) when trying to connect

So its taken a different host there when re-adding it. 

I will take a look at your source code when I get a free minute today and see if I can spot the problem, I was going to see if I can edit the source myself anyway to make the config file more accessible so its quicker to make changes as I find added 40 databases through the GUI takes a very long time.

**Comment by cbaerike** [comment]
Hi,

The config file is stored at C:\ProgramData\MySQLBackup\Configuration .
Feel free to edit the XML by hand if the GUI takes too long.

I've looked at the "Modify Database" issue, and am just pushing a fix.

**Comment by cbaerike** [comment]
Fixed in 1.4.3: https://github.com/cbaerike/MySQL-Backup-Manager/releases
